export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';

export const ADD_QUESTION = 'ADD_QUESTIONS';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTIONS_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTIONS_ERROR';

export const RESET_QUESTION_STATUS = 'RESET_QUESTION_STATUS';

export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS';
export const ADD_ANSWER_ERROR = 'ADD_ANSWER_ERROR';

export const RESET_ANSWER_STATUS = 'RESET_ANSWER_STATUS';

export const REPORT_ANSWER = 'REPORT_ANSWER';
export const REPORT_ANSWER_SUCCESS = 'REPORT_ANSWER_SUCCESS';
export const REPORT_ANSWER_ERROR = 'REPORT_ANSWER_ERROR';

export const ADD_HELPFUL_QUESTION = 'ADD_HELPFUL_QUESTION';
export const ADD_HELPFUL_QUESTION_SUCCESS = 'ADD_HELPFUL_QUESTION_SUCCESS';
export const ADD_HELPFUL_QUESTION_ERROR = 'ADD_HELPFUL_QUESTION_ERROR';

export const ADD_HELPFUL_ANSWER = 'ADD_HELPFUL_ANSWER';
export const ADD_HELPFUL_ANSWER_SUCCESS = 'ADD_HELPFUL_ANSWER_SUCCESS';
export const ADD_HELPFUL_ANSWER_ERROR = 'ADD_HELPFUL_ANSWER_ERROR';



