export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';


export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_ANSWERS_ERROR = 'GET_ANSWERS_ERROR';

export const PRODUCT_NAME = 'PRODUCT_NAME';
export const SHOW_ANSWERS = 'SHOW_ANSWERS';
export const HELPFUL_ANSWER = 'HELPFUL_ANSWER';
export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_ANSWER = 'ADD_ANSWER';
export const REPORT_ANSWER = 'REPORT_ANSWER';

